version: '3.8'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  cache:
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PW}
    volumes:
      - cache-data:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  app:
    depends_on:
      - db
      - cache
    build: .
    restart: unless-stopped
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PW=${REDIS_PW}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - ${PORT}:${PORT}

volumes:
  db-data:
  cache-data: