module.exports = {
  CREATE: "POST /post/create",
  UPDATE: "POST /post/update",
  DELETE: "PATCH /post/delete",
  DETAIL: "GET /post/detail",
  LIKE: "PATCH /post/like",
  DELETEDLIST: "GET /post/deletedList",
  RESTORE: "PATCH /post/restore",
  LIST: "GET /post/list",
  JOIN_EMAIL_CONFIRM: "POST /user/joinEmailConfirm",
  JOIN_RANDOM_NUM_CONFIRM: "POST /user/joinRandomNumberConfirm",
  JOIN: "POST /user/join",
  LOGIN: "POST /user/login",
  LOGIN_CONFIRM: "GET /user/loginConfirm",
  MYINFO: "GET /user/myInfo",
  LIKELIST: "GET /user/likeList",
};