module.exports = {
  BAD_REQUEST: { status: 400, message: "Bad Request", detail: "잘못된 요청입니다." },
  FORBIDDEN: { status: 403, message: "Forbidden", detail: "권한이 없는 사용자입니다." },
  NOT_FOUND: { status: 404, message: "Not Found", detail: "올바른 경로로 접속하세요." },
  INTERNAL_SERVER_ERROR: { status: 500, message: "Internal Server Error", detail: "서버 에러입니다. 관리자에게 문의하세요." },
  CREATE: "포스팅 되었습니다.",
  CREATE_FAIL: "포스팅에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  UPDATE: "게시글이 수정되었습니다.",
  UPDATE_FAIL: "게시글이 수정에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  DELETE: "게시글이 삭제되었습니다. 삭제된 게시글은 복원할 수 있습니다.",
  DELETE_FAIL: "게시글 삭제에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  DETAIL: "상세정보가 조회되었습니다.",
  DETAIL_FAIL: "상세정보 조회에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  LIKE: "해당 게시글에 좋아요를 표시했습니다.", 
  LIKE_CANCEL: "해당 게시글에 좋아요를 취소했습니다.",
  LIKE_FAIL: "좋아요 실패하였습니다. 잠시 후 다시 시도해주세요.",
  DELETE_LIST: "삭제된 게시물을 조회했습니다.",
  DELETE_LIST_NONE: "삭제된 게시물이 없습니다.",
  DELETE_LIST_FAIL: "삭제된 게시물을 불러오는데 실패하였습니다. 잠시 후 다시 시도해주세요.",
  RESTORE: "게시글이 복원되었습니다.",
  RESTORE_FAIL: "게시글 복원에 실패하였습니다. 잠시 후 다시 시도해주세요."
};