module.exports = {
  BAD_REQUEST: { status: 400, message: "Bad Request", detail: "잘못된 요청입니다." },
  FORBIDDEN: { status: 403, message: "Forbidden", detail: "권한이 없는 사용자입니다." },
  NOT_FOUND: { status: 404, message: "Not Found", detail: "올바른 경로로 접속하세요." },
  INTERNAL_SERVER_ERROR: { status: 500, message: "Internal Server Error", detail: "서버 에러입니다. 관리자에게 문의하세요." },
  CREATE: "포스팅 되었습니다.",
  CREATE_FAIL: "포스팅에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  UPDATE: "게시글이 수정되었습니다.",
  UPDATE_FAIL: "게시글이 수정에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  DELETE: "게시글이 삭제되었습니다. 삭제된 게시글은 복원할 수 있습니다.",
  DELETE_FAIL: "게시글 삭제에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  DETAIL: "상세정보가 조회되었습니다.",
  DETAIL_FAIL: "상세정보 조회에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  LIKE: "해당 게시글에 좋아요를 표시했습니다.", 
  LIKE_CANCEL: "해당 게시글에 좋아요를 취소했습니다.",
  LIKE_FAIL: "좋아요 실패하였습니다. 잠시 후 다시 시도해주세요.",
  DELETE_LIST: "삭제된 게시물을 조회했습니다.",
  DELETE_LIST_NONE: "삭제된 게시물이 없습니다.",
  DELETE_LIST_FAIL: "삭제된 게시물을 불러오는데 실패하였습니다. 잠시 후 다시 시도해주세요.",
  RESTORE: "게시글이 복원되었습니다.",
  RESTORE_FAIL: "게시글 복원에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  LIST: "게시글 목록을 조회했습니다.",
  LIST_NONE: "게시글이 없습니다.",
  LIST_FAIL: "게시글 조회에 실패하였습니다. 잠시 후 다시 시도해주세요.",
  JOIN_ID_DUPLICATE: "이미 사용중인 이메일입니다.",
  JOIN: "회원가입이 되었습니다.",
  JOIN_FAIL: "회원가입에 실패하였습니다.",
  LOGIN: "로그인 되었습니다.",
  LOGIN_NO_MATCH: "아이디나 비밀번호가 일치하지 않습니다.", 
  LOGIN_FAIL: "로그인에 실패하였습니다.",
  USER_INFO: "사용자 정보를 조회했습니다.",
  USER_INFO_FAIL: "사용자 정보 조회에 실패했습니다.",
  LIKE_LIST: "좋아요 누른 게시글을 조회했습니다.",
  LIKE_LIST_FAIL: "좋아요 누른 게시글을 조회에 실패했습니다.",
  LIKE_LIST_NONE: "좋아요 누른 게시글이 없습니다.",
  EMAIL_EMPTY: "이메일을 입력해주세요.",
  EMAIL_WARNING: "이메일 형식에 맞게 작성해주세요.", 
  PW_EMPTY: "비밀번호를 입력해주세요.",
  PW_WARNING: "최소 8자리 이상: 영어 대문자, 소문자, 숫자, 특수문자 중 3종류 조합", 
  CONFIRM_PW_EMPTY: "비밀번호 확인을 입력해주세요.", 
  COMFIRM_PW_WARNING: "비밀번호와 일치하지 않습니다.", 
  USERNAME_EMPTY: "이름을 입력해주세요.",
  USERNAME_LENGTH: "2글자이상 10글자미만으로 작성해주세요.",
  USERNAME_INCLUDE_SCRIPT: "이름에 특수문자를 포함할 수 없습니다.",
  LOGIN_REQUIRED: "로그인을 해주세요.",
  TITLE_EMPTY: "제목을 입력해주세요.",
  TITLE_LENGTH: "2글자이상 30글자 미만으로 입력해주세요.",
  CONTENT_EMPTY: "내용을 입력해주세요.",
  CONTENT_LENGTH: "2글자이상 255글자 미만으로 입력해주세요.",
  TITLE_INCLUDE_SCRIPT: "제목에 특정 특수문자를 포함할 수 없습니다.",
  CONTENT_INCLUDE_SCRIPT: "내용에 특정 특수문자를 포함할 수 없습니다.",
  HASHTAG_INCLUDE_SCRIPT: "해시태그에 특정 특수문자를 포함할 수 없습니다.",
  ACCESS_DENIED: "접속이 제한되었습니다.",
  NOT_BOT: "BOT 접근을 금지합니다.",
};